version: '3'

services:
  db:
    image: mariadb:10.3.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: profiles_service

  web:
    build: ./profiles_service
    command: python3 profiles_service/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db